### ISSUE TITLE
Create Error path for object attributes which are nil

### ISSUE THREAD

**Issue by corneliusellen** [slimecog/little-shop-redux#32]
For example, if user enters a merchant/item ID that does not exist, how does our program respond to this?

**Comment by slimecog** [comment]
have we addressed this issue yet?

**Comment by corneliusellen** [comment]
No, we still have a Sinatra error page when you go to edit or view a merchant or item and type in a merchant ID that DNE.
